// CRITICAL: Import LocationTrackingService FIRST to register background task
// This ensures TaskManager.defineTask() executes before any location updates arrive
import '@/lib/services/LocationTrackingService';
import { TrackingCoordinator } from '@/lib/services/TrackingCoordinator';
import { initTrackingConfig } from '@/lib/services/TrackingConfig';

import * as Notifications from 'expo-notifications';
import { DarkTheme, DefaultTheme, ThemeProvider as NavigationThemeProvider } from '@react-navigation/native';
import { Stack, router } from 'expo-router';
import { useEffect } from 'react';
import { StatusBar } from 'expo-status-bar';
import 'react-native-reanimated';

import { ThemeProvider, useTheme } from '@/contexts/ThemeContext';
import { AuthProvider } from '@/contexts/AuthContext';
import { UnitsProvider } from '@/contexts/UnitsContext';
import { TrackingProvider } from '@/contexts/TrackingContext';
import { QueryProvider } from '@/providers/QueryProvider';
import { useProtectedRoute } from '@/contexts/useProtectedRoute';
import { initializeMapbox } from '@/config/mapbox';

// Initialize i18n
import '@/lib/i18n';

// Configure how notifications are handled when the app is in the foreground.
// Trip-recording local notifications are always shown.
// Remote push notifications (from the server) are also shown.
// All other local notifications are suppressed.
Notifications.setNotificationHandler({
  handleNotification: async (notification) => {
    const isTripRecording = notification.request.identifier?.startsWith('trip-recording-');
    // Remote pushes have a trigger type of 'push'; local ones have 'calendar', 'interval', etc.
    const isRemotePush =
      notification.request.trigger != null &&
      (notification.request.trigger as { type?: string }).type === 'push';
    const data = notification.request.content.data as any;
    const isTripCompletion =
      data?.type === 'trip_completed' || data?.type === 'rate_trip';
    const shouldShow = isTripRecording || isRemotePush || isTripCompletion;
    return {
      shouldShowAlert: shouldShow,
      shouldShowBanner: shouldShow,
      shouldShowList: shouldShow,
      shouldPlaySound: isRemotePush,
      shouldSetBadge: false,
    };
  },
});

// Initialize Mapbox
initializeMapbox();

export const unstable_settings = {
  // Start with auth flow - will be changed to (tabs) after login
  initialRouteName: '(auth)',
};

function RootLayoutNav() {
  const { colorScheme } = useTheme();
  useProtectedRoute();

  // Initialize TrackingCoordinator and remote tracking config early.
  useEffect(() => {
    TrackingCoordinator.init().catch(err => console.error('[App] TrackingCoordinator init failed:', err));
    initTrackingConfig().catch(err => console.warn('[App] TrackingConfig init failed:', err));
  }, []);

  // Handle taps on push notifications — route to the relevant screen.
  // Backend sends snake_case keys (club_id, post_id) and these exact type strings.
  useEffect(() => {
    const subscription = Notifications.addNotificationResponseReceivedListener((response) => {
      const data = response.notification.request.content.data as {
        type?: string;
        // Local trip notifications (generated by frontend TripManager — camelCase)
        tripId?: string | number;
        // Backend club/post notifications — snake_case
        club_id?: string | number;
        post_id?: string | number;
        request_id?: string | number;
      } | null;

      if (data?.type === 'trip_completed' && data?.tripId) {
        router.replace(`/home/trip-detail?id=${data.tripId}`);
      } else if (data?.type === 'rate_trip' && data?.tripId) {
        router.replace(`/home/rate-route?id=${data.tripId}`);
      } else if (
        (data?.type === 'post_liked' || data?.type === 'post_commented' || data?.type === 'club_post') &&
        data?.post_id
      ) {
        router.replace(`/feed/post-detail?id=${data.post_id}`);
      } else if (data?.type === 'join_request' && data?.club_id) {
        // Admin: someone requested to join their private group
        router.replace(`/clubs/pending-requests?id=${data.club_id}`);
      } else if (data?.type === 'request_accepted' && data?.club_id) {
        // User: their join request was approved
        router.replace(`/clubs/${data.club_id}`);
      } else if (data?.type === 'request_rejected' && data?.club_id) {
        // User: their join request was declined
        router.replace(`/clubs/${data.club_id}`);
      }
    });
    return () => subscription.remove();
  }, []);

  return (
    <NavigationThemeProvider value={colorScheme === 'dark' ? DarkTheme : DefaultTheme}>
      <Stack screenOptions={{ headerShown: false }}>
        <Stack.Screen name="(auth)" options={{ headerShown: false }} />
        <Stack.Screen name="(onboarding)" options={{ headerShown: false }} />
        <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
        <Stack.Screen name="modal" options={{ presentation: 'modal', title: 'Modal' }} />
        <Stack.Screen
          name="modals/quick-actions-modal"
          options={{
            presentation: 'transparentModal',
            animation: 'fade',
            headerShown: false,
          }}
        />
        <Stack.Screen
          name="feedback"
          options={{
            presentation: 'card',
            headerShown: false,
          }}
        />
      </Stack>
      <StatusBar style={colorScheme === 'dark' ? 'light' : 'dark'} />
    </NavigationThemeProvider>
  );
}

export default function RootLayout() {
  return (
    <ThemeProvider>
      <AuthProvider>
        <QueryProvider>
          <UnitsProvider>
            <TrackingProvider>
              <RootLayoutNav />
            </TrackingProvider>
          </UnitsProvider>
        </QueryProvider>
      </AuthProvider>
    </ThemeProvider>
  );
}
