/**
 * Parity test: Python featurizer_v1 + XGBoost inference vs the TypeScript port.
 *
 * Loads `radzi-ml-project/results/parity_fixtures.json` (generated by
 * `pipeline/export.py`), runs the same windows through the TS `extractFeatures`
 * and TS `loadXgbBooster`, and asserts:
 *   1. Per-feature absolute error < 1e-3 on every one of 20×136 values.
 *   2. Predicted class matches exactly for all 20 fixtures.
 *   3. Predicted probabilities match within 1e-3.
 *
 * Runners:
 *   - jest (preferred): `npx jest lib/activity/__tests__/parity.test.ts`
 *   - tsx (no setup): `npx tsx lib/activity/__tests__/parity.test.ts`
 *     — will execute the parity block below and throw on failure.
 */

import * as path from 'node:path';
import * as fs from 'node:fs';

import { extractFeatures, DEFAULT_FEATURIZER_CONFIG } from '../featurize';
import { loadXgbBooster, type XgbRawModel } from '../xgbTree';

type Fixture = {
  window: number[][];
  features: number[];
  y_true: number;
  y_pred: number;
  proba: number[];
};

type FixturesFile = {
  sample_rate_hz: number;
  window_size: number;
  sensors: string[];
  classes: string[];
  feature_names: string[];
  fixtures: Fixture[];
};

const FIXTURES_PATH = path.resolve(
  __dirname,
  '..',
  '..',
  '..',
  '..',
  'radzi-ml-project',
  'results',
  'parity_fixtures.json',
);

const MODEL_PATH = path.resolve(__dirname, '..', '..', '..', 'assets', 'model', 'best_model.json');

// Relative tolerance: `|ts - py| / (1 + |py|) < 1e-4` per feature.
// Raw float32 totals like `total_power` can hit 10^6, where 1 ULP ≈ 0.5,
// so an absolute tolerance alone is meaningless.
const FEATURE_REL_TOLERANCE = 1e-4;
const PROB_TOLERANCE = 1e-3;

function loadFixtures(): FixturesFile {
  const raw = fs.readFileSync(FIXTURES_PATH, 'utf8');
  return JSON.parse(raw) as FixturesFile;
}

function loadModel(): XgbRawModel {
  const raw = fs.readFileSync(MODEL_PATH, 'utf8');
  return JSON.parse(raw) as XgbRawModel;
}

function flattenWindow(window: number[][]): Float32Array {
  const rows = window.length;
  const cols = window[0].length;
  const out = new Float32Array(rows * cols);
  for (let i = 0; i < rows; i++) {
    for (let j = 0; j < cols; j++) {
      out[i * cols + j] = window[i][j];
    }
  }
  return out;
}

export function runParityCheck(): {
  maxFeatureAbsErr: number;
  maxFeatureRelErr: number;
  maxProbErr: number;
  labelMismatches: number;
} {
  const data = loadFixtures();
  const booster = loadXgbBooster(loadModel());

  if (data.fixtures.length === 0) {
    throw new Error('No fixtures found');
  }

  const config = {
    ...DEFAULT_FEATURIZER_CONFIG,
    sampleRateHz: data.sample_rate_hz,
    windowSize: data.window_size,
    nFeatures: data.feature_names.length,
  };

  let maxFeatureAbsErr = 0;
  let maxFeatureRelErr = 0;
  let maxFeatureErrIdx = -1;
  let maxFeatureErrFx = -1;
  let maxProbErr = 0;
  let labelMismatches = 0;

  data.fixtures.forEach((fx, fIdx) => {
    const buf = flattenWindow(fx.window);
    const tsFeatures = extractFeatures(buf, config);

    if (tsFeatures.length !== fx.features.length) {
      throw new Error(
        `fixture ${fIdx}: TS produced ${tsFeatures.length} features, Python ${fx.features.length}`,
      );
    }

    for (let i = 0; i < tsFeatures.length; i++) {
      const py = fx.features[i];
      const ts = tsFeatures[i];
      const absErr = Math.abs(ts - py);
      const relErr = absErr / (1 + Math.abs(py));
      if (absErr > maxFeatureAbsErr) maxFeatureAbsErr = absErr;
      if (relErr > maxFeatureRelErr) {
        maxFeatureRelErr = relErr;
        maxFeatureErrIdx = i;
        maxFeatureErrFx = fIdx;
      }
    }

    const probs = booster.predictProba(tsFeatures);
    for (let c = 0; c < probs.length; c++) {
      const err = Math.abs(probs[c] - fx.proba[c]);
      if (err > maxProbErr) maxProbErr = err;
    }

    let argmax = 0;
    let best = probs[0];
    for (let c = 1; c < probs.length; c++) {
      if (probs[c] > best) {
        best = probs[c];
        argmax = c;
      }
    }
    if (argmax !== fx.y_pred) labelMismatches++;
  });

  console.log(
    `[parity] maxFeatureAbsErr=${maxFeatureAbsErr.toExponential(3)} maxFeatureRelErr=${maxFeatureRelErr.toExponential(3)} (fx ${maxFeatureErrFx}, feat ${maxFeatureErrIdx}) maxProbErr=${maxProbErr.toExponential(3)} labelMismatches=${labelMismatches}/${data.fixtures.length}`,
  );

  return { maxFeatureAbsErr, maxFeatureRelErr, maxProbErr, labelMismatches };
}

// Jest-compatible block (guarded so tsx can import this file without jest).
declare const describe: unknown;
declare const it: unknown;
declare const expect: unknown;

if (typeof describe === 'function' && typeof it === 'function' && typeof expect === 'function') {
  // @ts-ignore — describe/it/expect provided by jest at runtime
  describe('ML parity (TS ports match Python featurizer_v1 + XGBoost)', () => {
    // @ts-ignore
    it('matches features within 1e-4 relative and predictions exactly', () => {
      const result = runParityCheck();
      // @ts-ignore
      expect(result.maxFeatureRelErr).toBeLessThan(FEATURE_REL_TOLERANCE);
      // @ts-ignore
      expect(result.maxProbErr).toBeLessThan(PROB_TOLERANCE);
      // @ts-ignore
      expect(result.labelMismatches).toBe(0);
    });
  });
}

// tsx / standalone runner.
const isDirectRun =
  typeof require !== 'undefined' && typeof module !== 'undefined' && require.main === module;
if (isDirectRun) {
  const { maxFeatureRelErr, maxProbErr, labelMismatches } = runParityCheck();
  if (maxFeatureRelErr >= FEATURE_REL_TOLERANCE) {
    console.error(`FAIL: feature rel error ${maxFeatureRelErr} >= ${FEATURE_REL_TOLERANCE}`);
    process.exit(1);
  }
  if (maxProbErr >= PROB_TOLERANCE) {
    console.error(`FAIL: proba error ${maxProbErr} >= ${PROB_TOLERANCE}`);
    process.exit(1);
  }
  if (labelMismatches > 0) {
    console.error(`FAIL: ${labelMismatches} label mismatches`);
    process.exit(1);
  }
  console.log('OK');
}
